name: Website Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy Website to S3
        run: aws s3 sync ./index.html s3://newfi.io --include "./assets/" --include "./images/" --include "./src/" --exclude "*" --delete
      - name: Clean Website Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_WEBSITE_DIST_ID }} --paths "/*"
